// Generated by delombok at Tue Jul 03 21:06:33 NOVT 2018
package org.statesync.spring.ws.listeners;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.messaging.simp.stomp.StompHeaderAccessor;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.messaging.SessionConnectedEvent;
import org.statesync.spring.SpringSyncService;

@Component
public class StompSessionConnectedEventListener implements ApplicationListener<SessionConnectedEvent>
{
	@java.lang.SuppressWarnings("all")
	private static final java.util.logging.Logger log = java.util.logging.Logger
			.getLogger(StompSessionConnectedEventListener.class.getName());
	@Autowired
	private SpringSyncService syncService;

	@Override
	public void onApplicationEvent(final SessionConnectedEvent event)
	{
		this.syncService.onSessionConnected(event);
		final StompHeaderAccessor headerAccessor = StompHeaderAccessor.wrap(event.getMessage());
		log.severe(headerAccessor.toString());
	}
}
